#!/bin/bash
# AutoMQ Software Kubernetes Helm Installation Script
# Supports: curl -sSL https://raw.githubusercontent.com/AutoMQ/automq-examples/main/software-examples/kubernetes/local/helm/install.sh | bash

set -e

# GitHub raw URL base
GITHUB_RAW_BASE="https://raw.githubusercontent.com/AutoMQ/automq-examples/main/software-examples/kubernetes/local/helm"

# Configuration
AUTOMQ_VERSION="5.3.4"
MINIO_USER="admin"
MINIO_PASSWORD="automq_demo_secret"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

print_info() {
    printf "${GREEN}[INFO]${NC} %s\n" "$1"
}

print_warn() {
    printf "${YELLOW}[WARN]${NC} %s\n" "$1"
}

print_error() {
    printf "${RED}[ERROR]${NC} %s\n" "$1"
}

print_step() {
    printf "\n${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
    printf "${CYAN}[STEP %s]${NC} %s\n" "$1" "$2"
    printf "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n\n"
}

print_config() {
    printf "  ${CYAN}%-25s${NC} %s\n" "$1:" "$2"
}

print_header() {
    echo ""
    printf "${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}\n"
    printf "${BLUE}║${NC}     ${CYAN}AutoMQ Local Deployment - One-Click Installation${NC}        ${BLUE}║${NC}\n"
    printf "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}\n"
    echo ""
}

print_summary() {
    printf "\n${BLUE}╔══════════════════════════════════════════════════════════════╗${NC}\n"
    printf "${BLUE}║${NC}                  ${GREEN}Installation Complete!${NC}                      ${BLUE}║${NC}\n"
    printf "${BLUE}╚══════════════════════════════════════════════════════════════╝${NC}\n\n"
}

# Step 1: Check prerequisites
check_prerequisites() {
    print_step "1/6" "Checking Prerequisites"
    
    local has_error=0

    # Check curl
    printf "  Checking curl... "
    if ! command -v curl &> /dev/null; then
        printf "${RED}NOT FOUND${NC}\n"
        print_error "curl is not installed."
        has_error=1
    else
        printf "${GREEN}OK${NC}\n"
    fi

    # Check kubectl
    printf "  Checking kubectl... "
    if ! command -v kubectl &> /dev/null; then
        printf "${RED}NOT FOUND${NC}\n"
        print_error "kubectl is not installed. Please install kubectl first."
        print_info "  Installation guide: https://kubernetes.io/docs/tasks/tools/"
        has_error=1
    else
        printf "${GREEN}OK${NC} ($(kubectl version --client --short 2>/dev/null | head -1 || echo "installed"))\n"
    fi

    # Check helm
    printf "  Checking helm... "
    if ! command -v helm &> /dev/null; then
        printf "${RED}NOT FOUND${NC}\n"
        print_error "helm is not installed. Please install helm first."
        print_info "  Installation guide: https://helm.sh/docs/intro/install/"
        has_error=1
    else
        printf "${GREEN}OK${NC} ($(helm version --short 2>/dev/null))\n"
    fi

    # Check kubernetes cluster connectivity
    printf "  Checking Kubernetes cluster... "
    if ! kubectl cluster-info &> /dev/null; then
        printf "${RED}NOT ACCESSIBLE${NC}\n"
        print_error "Cannot connect to Kubernetes cluster."
        has_error=1
    else
        local node_count
        node_count=$(kubectl get nodes --no-headers 2>/dev/null | wc -l | tr -d ' ')
        printf "${GREEN}OK${NC} ($node_count nodes)\n"
    fi

    if [ $has_error -eq 1 ]; then
        echo ""
        print_error "Prerequisites check failed. Please resolve the issues above and try again."
        exit 1
    fi

    print_info "All prerequisites satisfied!"
}

# Step 2: Download helper scripts
download_scripts() {
    print_step "2/6" "Downloading Helper Scripts"
    
    curl -sSL -o verify.sh "${GITHUB_RAW_BASE}/verify.sh"
    chmod +x verify.sh
    print_info "✓ Downloaded verify.sh"

    curl -sSL -o cleanup.sh "${GITHUB_RAW_BASE}/cleanup.sh"
    chmod +x cleanup.sh
    print_info "✓ Downloaded cleanup.sh"
}

# Step 3: Detect architecture and generate values
generate_values() {
    print_step "3/6" "Generating Configuration"
    
    # Detect CPU architecture
    local arch
    arch=$(uname -m)
    case $arch in
        arm64|aarch64)
            NODE_ARCH="arm64"
            ;;
        x86_64|amd64)
            NODE_ARCH="amd64"
            ;;
        *)
            NODE_ARCH="amd64"
            ;;
    esac
    
    print_info "Detected CPU architecture: $NODE_ARCH"
    print_info "Generating automq-values.yaml..."
    
    cat <<EOF > automq-values.yaml
# AutoMQ Helm Values - Generated by install.sh
# Architecture: ${NODE_ARCH}

global:
  automqInstanceId: "automq-demo-cluster"
  cloudProvider:
    name: "noop"
    credentials: "static://?accessKey=admin&secretKey=automq_demo_secret"
  nodeAffinities:
    - key: "kubernetes.io/arch"
      values:
        - "${NODE_ARCH}"
  config: |
    s3.ops.buckets=0@s3://automq-ops?region=us-east-1&endpoint=http://minio.default.svc.cluster.local:9000&pathStyle=true
    s3.data.buckets=0@s3://automq-data?region=us-east-1&endpoint=http://minio.default.svc.cluster.local:9000&pathStyle=true
    s3.wal.path=0@s3://automq-data?region=us-east-1&endpoint=http://minio.default.svc.cluster.local:9000&pathStyle=true

controller:
  replicas: 3
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  env:
    - name: "KAFKA_S3_ACCESS_KEY"
      value: "admin"
    - name: "KAFKA_S3_SECRET_KEY"
      value: "automq_demo_secret"
    - name: "KAFKA_HEAP_OPTS"
      value: "-Xmx2g -Xms2g"
  persistence:
    wal:
      enabled: false

broker:
  replicas: 0
  env:
    - name: "KAFKA_S3_ACCESS_KEY"
      value: "admin"
    - name: "KAFKA_S3_SECRET_KEY"
      value: "automq_demo_secret"
  persistence:
    wal:
      enabled: false
EOF

    print_info "✓ Configuration file generated"
    echo ""
    echo "  Configuration summary:"
    print_config "Architecture" "$NODE_ARCH"
    print_config "Controller Replicas" "3"
    print_config "Controller Memory" "2Gi - 4Gi"
    print_config "Controller CPU" "1 - 2 cores"
    print_config "Heap Size" "2GB"
}

# Step 4: Install MinIO
install_minio() {
    print_step "4/6" "Installing MinIO (Object Storage)"
    
    # Add helm repo
    print_info "Adding MinIO helm repository..."
    helm repo add minio https://charts.min.io/ > /dev/null 2>&1 || true
    helm repo update > /dev/null 2>&1
    
    # Check if already installed
    if helm status minio &> /dev/null; then
        print_warn "MinIO is already installed, skipping..."
        return
    fi
    
    echo ""
    echo "  MinIO configuration:"
    print_config "Root User" "$MINIO_USER"
    print_config "Root Password" "$MINIO_PASSWORD"
    print_config "Data Bucket" "automq-data"
    print_config "Ops Bucket" "automq-ops"
    print_config "Mode" "standalone"
    print_config "Persistence" "disabled"
    echo ""
    
    print_info "Installing MinIO..."
    helm install minio minio/minio \
        --set rootUser=admin \
        --set rootPassword=automq_demo_secret \
        --set "buckets[0].name=automq-data,buckets[0].policy=none,buckets[0].purge=false" \
        --set "buckets[1].name=automq-ops,buckets[1].policy=none,buckets[1].purge=false" \
        --set mode=standalone \
        --set service.type=ClusterIP \
        --set persistence.enabled=false \
        --set resources.requests.memory=512Mi \
        --set resources.requests.cpu=250m \
        --set resources.limits.memory=2Gi \
        --set resources.limits.cpu=2 \
        --wait \
        --timeout 5m \
        > /dev/null
    
    print_info "✓ MinIO installed successfully"
}

# Step 5: Install AutoMQ
install_automq() {
    print_step "5/6" "Installing AutoMQ"
    
    # Check if already installed
    if helm status automq &> /dev/null; then
        print_warn "AutoMQ is already installed, skipping..."
        return
    fi
    
    echo ""
    echo "  AutoMQ configuration:"
    print_config "Version" "$AUTOMQ_VERSION"
    print_config "Chart" "oci://automq.azurecr.io/helm/automq-enterprise-chart"
    print_config "Values File" "automq-values.yaml"
    echo ""
    
    print_info "Installing AutoMQ (this may take a few minutes)..."
    helm install automq oci://automq.azurecr.io/helm/automq-enterprise-chart \
        --version "$AUTOMQ_VERSION" \
        -f automq-values.yaml \
        --wait \
        --timeout 10m \
        > /dev/null
    
    print_info "✓ AutoMQ installed successfully"
}

# Step 6: Verify installation
verify_installation() {
    print_step "6/6" "Verifying Installation"
    
    print_info "Checking pod status..."
    echo ""
    kubectl get pods -l app.kubernetes.io/name=automq-enterprise
    echo ""
    
    # Wait for pods to be ready
    local ready_pods
    local total_pods
    ready_pods=$(kubectl get pods -l app.kubernetes.io/name=automq-enterprise --no-headers 2>/dev/null | grep -c "Running" || echo "0")
    total_pods=$(kubectl get pods -l app.kubernetes.io/name=automq-enterprise --no-headers 2>/dev/null | wc -l | tr -d ' ')
    
    if [ "$ready_pods" -ne "$total_pods" ]; then
        print_info "Waiting for all pods to be ready..."
        kubectl wait --for=condition=Ready pods -l app.kubernetes.io/name=automq-enterprise --timeout=300s
    fi
    
    print_info "✓ All AutoMQ pods are running"
}

# Print final summary
print_final_summary() {
    print_summary
    
    echo "  Deployed components:"
    print_config "MinIO" "Running (standalone mode)"
    print_config "AutoMQ Controllers" "3 replicas"
    echo ""
    
    echo "  Access information:"
    print_config "Bootstrap Server" "automq-automq-enterprise-controller-headless:9092"
    print_config "MinIO Console" "kubectl port-forward svc/minio-console 9001:9001"
    echo ""
    
    echo "  Quick test commands:"
    echo ""
    echo "  # Create a topic"
    echo "  kubectl run kafka-client --rm -it --restart=Never --image=confluentinc/cp-kafka:latest -- \\"
    echo "    kafka-topics --bootstrap-server automq-automq-enterprise-controller-headless:9092 \\"
    echo "    --create --topic test-topic --partitions 3 --replication-factor 1"
    echo ""
    echo "  # List topics"
    echo "  kubectl run kafka-list --rm -it --restart=Never --image=confluentinc/cp-kafka:latest -- \\"
    echo "    kafka-topics --bootstrap-server automq-automq-enterprise-controller-headless:9092 --list"
    echo ""
    echo "  Cleanup:"
    echo "  ./cleanup.sh"
    echo ""
}

# Main
main() {
    print_header
    check_prerequisites
    download_scripts
    generate_values
    install_minio
    install_automq
    verify_installation
    print_final_summary
}

main "$@"
